import { type VoiceParticipant, type PeerDiagnosticsStats, UserAudioState, VoiceConnectionState } from '@echo/shared';
export type VoiceInputMode = 'vad' | 'ptt';
export interface VoiceState {
    currentGroupId: string | null;
    currentGroupName: string | null;
    currentChannelId: string | null;
    currentChannelName: string | null;
    connectionStatus: 'disconnected' | 'connecting' | 'connected' | VoiceConnectionState;
    audioState: UserAudioState;
    isMuted: boolean;
    isDeafened: boolean;
    isSpeaking: boolean;
    isCameraActive: boolean;
    cameraStreams: Record<string, MediaStream>;
    pingMs: number;
    inputMode: VoiceInputMode;
    pttKey: string;
    pttKeyDisplay: string;
    pttReleaseDelay: number;
    isPttActive: boolean;
    channelParticipants: Record<string, VoiceParticipant[]>;
    diagnostics: Record<string, PeerDiagnosticsStats>;
    isDiagnosticsOpen: boolean;
    localAudioLevel: number;
    isMicUnavailable: boolean;
    setConnecting: (groupId: string, groupName: string, channelId: string, channelName: string) => void;
    setConnected: (channelId: string) => void;
    setDisconnected: () => void;
    setAudioState: (state: UserAudioState, myUserId?: string) => void;
    setMuted: (muted: boolean, myUserId?: string) => void;
    setDeafened: (deafened: boolean, myUserId?: string) => void;
    setSpeaking: (speaking: boolean, myUserId?: string) => void;
    setCameraActive: (active: boolean) => void;
    setPeerCameraStream: (peerId: string, stream: MediaStream) => void;
    removePeerCameraStream: (peerId: string) => void;
    setPingMs: (ping: number) => void;
    setLocalAudioLevel: (level: number) => void;
    setIsMicUnavailable: (unavailable: boolean) => void;
    setInputMode: (mode: VoiceInputMode) => void;
    setPttKey: (key: string, display: string) => void;
    setPttReleaseDelay: (delay: number) => void;
    setPttActive: (active: boolean) => void;
    setChannelParticipants: (channelId: string, participants: VoiceParticipant[]) => void;
    addChannelParticipant: (channelId: string, participant: VoiceParticipant) => void;
    removeChannelParticipant: (channelId: string, userId: string) => void;
    updateChannelParticipantState: (channelId: string, userId: string, state: {
        muted: boolean;
        deafened: boolean;
        speaking: boolean;
        camera?: boolean;
    }) => void;
    setDiagnostics: (diagnostics: Record<string, PeerDiagnosticsStats>) => void;
    setDiagnosticsOpen: (open: boolean) => void;
}
export declare const useVoiceStore: import("zustand").UseBoundStore<import("zustand").StoreApi<VoiceState>>;
