import { type VoiceSignalData, type VoiceParticipant } from '@echo/shared';
export interface AudioProcessingSettings {
    rnnoise: boolean;
    noiseSuppression: boolean;
    echoCancellation: boolean;
    autoGainControl: boolean;
    highpassFilter: boolean;
    typingSuppression: boolean;
}
declare class WebRTCVoiceService {
    private localStream;
    private rawLocalStream;
    private rnnoiseProcessorInstance;
    private rawTestMicStream;
    private testMicRnnoiseInstance;
    private audioContext;
    private analyser;
    private vadInterval;
    private diagnosticsInterval;
    private peers;
    private peerAudioElements;
    private peerDisplayNames;
    private pendingCandidates;
    private prevStats;
    private iceServers;
    private currentGroupId;
    private currentChannelId;
    private lastSpeakingState;
    private speakingSilenceTimer;
    private audioProcessing;
    private selectedInputDeviceId;
    private selectedOutputDeviceId;
    private selectedVideoDeviceId;
    private localCameraStream;
    private outputVolume;
    private testMicStream;
    private testMicAudioEl;
    private loopbackSenderPc;
    private loopbackReceiverPc;
    private loopbackAudioEl;
    init(): Promise<void>;
    join(groupId: string, groupName: string, channelId: string, channelName: string): Promise<void>;
    leave(): void;
    handleUserJoined(channelId: string, joinedUserId: string, joinedDisplayName: string, existingParticipants: VoiceParticipant[]): void;
    handleUserLeft(channelId: string, leftUserId: string): void;
    handleSignal(fromUserId: string, signal: VoiceSignalData, channelId?: string): Promise<void>;
    private syncTracks;
    private initiateOffer;
    private handleOffer;
    private handleAnswer;
    private handleCandidate;
    private getOrCreatePeerConnection;
    updateConnectionStatusGate(): void;
    updateAudioTrackState(): void;
    setPttActive(active: boolean): void;
    setInputMode(mode: 'vad' | 'ptt'): void;
    toggleMute(): void;
    toggleDeafen(): void;
    private setupVAD;
    private setLocalSpeaking;
    private startDiagnostics;
    private pollDiagnostics;
    getAudioDevices(): Promise<{
        inputs: MediaDeviceInfo[];
        outputs: MediaDeviceInfo[];
    }>;
    getAudioProcessingSettings(): AudioProcessingSettings;
    getAudioConstraints(deviceId?: string | null): MediaTrackConstraints;
    private attachRNNoiseToLocalStream;
    updateAudioProcessingSettings(newSettings: Partial<AudioProcessingSettings>): Promise<void>;
    private reacquireLocalAudio;
    setInputDevice(deviceId: string): Promise<void>;
    setOutputDevice(deviceId: string): Promise<void>;
    setOutputVolume(volume: number): void;
    getOutputVolume(): number;
    getInputDeviceId(): string | null;
    getOutputDeviceId(): string | null;
    startLoopbackTest(): Promise<void>;
    stopLoopbackTest(): void;
    restartLoopbackTest(): Promise<void>;
    setSelfLoopbackActive(active: boolean): void;
    toggleSelfLoopback(): void;
    testMicrophone(onLevel: (rms: number) => void, enableLoopback?: boolean): () => void;
    setTestMicLoopback(enable: boolean): void;
    getLocalCameraStream(): MediaStream | null;
    getVideoDeviceId(): string | null;
    getVideoDevices(): Promise<MediaDeviceInfo[]>;
    setVideoDevice(deviceId: string): Promise<void>;
    testCamera(videoElement: HTMLVideoElement): () => void;
    toggleCamera(enable?: boolean): Promise<boolean>;
}
export declare const webrtcService: WebRTCVoiceService;
export {};
